import raw from "@/data/fingerprint.json";

/** Shape of the generated `src/data/fingerprint.json`. */
export interface FingerprintData {
	configured: boolean;
	/** Uppercase hex, 40 chars (v4) or 64 chars (v5). Present only when configured. */
	fingerprint?: string;
	/** Site-root-relative path to the public key, e.g. "keys/public.asc". */
	keyPath?: string;
}

export const fingerprint: FingerprintData = raw as FingerprintData;

/**
 * True only when a real key was imported at build time and produced a valid fingerprint.
 * The JSON is generated by scripts/derive-fingerprint.mjs; this never invents values.
 */
export function isPgpConfigured(): boolean {
	if (fingerprint.configured !== true) return false;
	if (typeof fingerprint.fingerprint !== "string") return false;
	return /^[0-9A-Fa-f]{40}$|^[0-9A-Fa-f]{64}$/.test(fingerprint.fingerprint);
}

/** Group a hex fingerprint in fours for display: `ABCD EFGH ...`. */
export function formatFingerprint(value: string): string {
	const clean = value.replace(/\s+/g, "").toUpperCase();
	const groups = clean.match(/.{1,4}/g);
	return groups ? groups.join(" ") : clean;
}
